<?php
foreach($this->LstClasses as $val)
{
	/*
	$prixClass = new Zend_Form_Element_Text('class_'.$val['idClasse']);
	$prixClass->setValue('000.00');
	$prixClass->setLabel($val['nomClasse'].' :');
	$prixClass->setDescription('€ (nombre de place disponible : '.$val['nbPlaces'].')');
	$prixClass->addValidator('float');
	
	$prixClass->addDecorators(array(
		array('HtmlTag', array('tag' => 'dd', 'class' => 'prix', 'id' => 'class_'.$val['idClasse'].'-element')),
		array('Label', array('tag' => 'dt', 'tagClass' => 'prix')),
		array('Description', array('tag' => 'p'))
	));
	//$FormPlanifier->addElement($prixClass);
	*/
	
	echo '<dt id="class_'.$val['idClasse'].'-label" class="prix"><label class="optional" for="class_'.$val['idClasse'].'">'.$val['nomClasse'].' :</label></dt>';
	echo "\n";
	echo '<dd id="class_'.$val['idClasse'].'-element" class="prix">';
		echo '<input id="class_'.$val['idClasse'].'" type="number" min="000.00" step="0.01" name="class_'.$val['idClasse'].'" />';
		echo '<p class="hint">€&nbsp;&nbsp;&nbsp;(nombre de place disponible : '.$val['nbPlaces'].')</p>';
		echo '<p class="PlanifierEmptyPrix"></p>';
	echo '</dd>';
	echo "\n";
}
?>