<div id="appli">
    <h1 id="h1_dl_appli">Téléchargez notre application pour votre smartphone 
        <span id="andro">
             <img id="imgqrcode" src="<?php echo $this->baseUrl();?>/img/logoandroid.png" alt="Android"/>
        </span> !</h1>
    <br><br>
    <div id="div_qrcode">
        <center>
            <p id="p_android">
            Cliquez <strong><a href="<?php echo $this->baseUrl();?>/android/maintenance.apk" id="lien_appli">ici</a></strong>
            ou scannez ce QR code :
            </p>
            <div id="bg_qrcode">
               <img id="imgqrcode" src="<?php echo $this->baseUrl();?>/img/maintenanceAndroid.png" alt="application android"/>
            </div>
        </center>
    </div>
</div>