<?php
    $espaceSession = new Zend_Session_Namespace('AjoutTechCourant');
            
    $verifAjout = $espaceSession->VerifAjout;
    if($verifAjout == false)
    {
        ?>
            <META HTTP-EQUIV="Refresh" CONTENT="5; URL=<?php $this->baseUrl(); ?>/technicien/ajoutertechnicien">
        <?php
    }
    else
    {
        ?>
            <META HTTP-EQUIV="Refresh" CONTENT="5; URL=<?php // $this->baseUrl(); ?>/technicien/gestiontechnicien">
        <?php
    }
    
    $message = $this->message;
    
    echo $message;
?>

<br>
<p>Redirection en cours... Veuillez patientez quelques secondes ou cliquez 
    <a href="<?php $this->baseUrl(); ?>/technicien/gestiontechnicien">ici</a>
</p>