<div id="tableau">    
    <table>
        <h2 id="centrer">Listing des techniciens</h2>
        <tr>
            <th>Matricule</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Adresse</th>
            <th>Date de naissance</th>
            <th>Modifier</th>
        </tr>
        <?php
            $lesTechs = $this->lesTechs;
            foreach ($lesTechs as $unTech) 
            {
                echo '<tr>';
                echo '<td>'.$unTech["matriculeTechnicien"].'</td>';
                echo '<td>'.$unTech["nomTechnicien"].'</td>';
                echo '<td>'.$unTech["prenomTechnicien"].'</td>';
                echo '<td>'.$unTech["adresseTechnicien"].'</td>';
                echo '<td>'.$unTech["dateNaissanceTechnicien"].'</td>';
                echo '<td>
                    <a href="'.$this->baseUrl().'/drh/modifiertechnicien/matricule/'.$unTech["matriculeTechnicien"].'" title="Modifier"><img src="'. $this->baseUrl() .'/img/pencil.png" /></a>';
                echo '</td>';
                echo '</tr>';
            }
        ?>   
    </table>
    <br>
    <a id="ajoutTech" class="bouton ajouter" href="<?php echo $this->baseUrl(); ?>/drh/ajoutertechnicien">Ajouter un technicien</a>
</div>