<h1>Breveter un pilote</h1><br />
<?php

     if(Services_verifAcces('DRH'))
     {

          echo '<div class="information">Si le brevet du pilote existe déjà, la date de validité sera modifiée. Sinon, un nouveau brevet sera créé.</div><br />';
          if (!empty($this->message))
          {
              echo $this->message[0]; 
          }
          echo '<p>Pour ajouter ou modifier un brevet d\'un pilote, remplissez le formulaire ci-dessous.</p><br />';
          echo $this->formHabiliter; 
          
     }
     else
     {
         echo '<div class="erreur">
                     Erreur !<br />
                     Vous n\'avez pas accès à cette page, veuillez vous identifier.<br />
                     <a href=\'/\'>Retour</a>
               </div>';
     }
?>

