<h1>Modifier un pilote</h1><br />
<?php

     if(Services_verifAcces('DRH'))
     {
          
          echo $this->message;
          echo $this->formPilote; 
          echo '<center><a href="'.$this->baseUrl().'/drh/personaviguant">Retour</a></center>';

     }
     else
     {
         echo '<div class="erreur">
                     Erreur !<br />
                     Vous n\'avez pas accès à cette page, veuillez vous identifier.<br />
                     <a href=\'/\'>Retour</a>
               </div>';
     }
?>

