<?php
    $espaceSession = new Zend_Session_Namespace('ModifTechChoisi');
            
    $matricule = $espaceSession->matriculeTech;
    $verifModif = $espaceSession->VerifModif;
    
    if($verifModif == false)
    {
        ?>
            <META HTTP-EQUIV="Refresh" CONTENT="5; URL=<?php $this->baseUrl(); ?>/drh/modifiertechnicien/matricule/<?php echo $matricule; ?>">
        <?php
    }
    else
    {
        ?>
            <META HTTP-EQUIV="Refresh" CONTENT="5; URL=<?php $this->baseUrl(); ?>/drh/gestiontechnicien">
        <?php
    }
        
    $message = $this->message;
    
    echo $message;
?>

<br>
<p>Redirection en cours... Veuillez patientez quelques secondes ou cliquez 
    <a href="<?php $this->baseUrl(); ?>/drh/gestiontechnicien">ici</a>
</p>