<h1>
    <?php
        echo $this->aeroportDepart['nomAeroport'];
        echo " (".$this->ligne['trigrammeAeroportDepart'].")";
        echo " -> ";
        echo $this->aeroportArrivee['nomAeroport'];
        echo " (".$this->ligne['trigrammeAeroportArrivee'].")";
    ?>
</h1><br /><br />

<div id="tableau">
    <table>
        <caption>Les vols à venir de cette ligne :</caption>
        <tr>
            <th>Départ prévu le</th>
            <th>Arrivée prévue le</th>
            <th>Escales</th>
            <th>Tarifs</th>
        </tr>
        <?php
            $locale = new Zend_Locale('fr_FR');
            foreach ($this->lesVols as $unVol)
            {
                $unVol['dateHeureDepartPrevueVol'] = new Zend_Date($unVol['dateHeureDepartPrevueVol'], false, $locale);          
                $unVol['dateHeureArriveePrevueVol'] = new Zend_Date($unVol['dateHeureArriveePrevueVol'],false, $locale);          
                echo "<tr>";
                echo "<td>".$unVol['dateHeureDepartPrevueVol']->toString('EEEE dd MMMM yyyy à HH:mm')."</td>";
                echo "<td>".$unVol['dateHeureArriveePrevueVol']->toString(' EEEE dd MMMM yyyy à HH:mm')."</td>";
                if ($unVol['nbEscales'] == 0)
                {
                    echo "<td>Aucune (ligne directe)</td>";
                }
                else
                {
                    echo "<td>".$unVol['nbEscales']." (détails)";
                    echo"<br />
                        
                    </td>";
                }
                echo "<td>";
                foreach ($this->lesTarifs[$unVol['idVol']] as $lesTarifsDuVol)
                {
                        echo $lesTarifsDuVol['nomClasse'];
                        echo " : ".$lesTarifsDuVol['prixUnitaire']." euros<br />";                        
                }
                echo"</td>";
                echo "</tr>";
            }
        ?>
    </table>
</div>
