<h1>
    <?php
        echo $this->aeroportDepart['nomAeroport'];
        echo " (".$this->ligne['trigrammeAeroportDepart'].")";
        echo " -> ";
        echo $this->aeroportArrivee['nomAeroport'];
        echo " (".$this->ligne['trigrammeAeroportArrivee'].")";
    ?>
</h1><br /><br />

<h2>Les vols</h2>

<div id="tableau">
    <table>
        <caption>Les vols à venir de cette ligne :</caption>
        <tr>
            <th>Départ prévu le</th>
            <th>Arrivée prévue le</th>
            <th>Nombre d'escales</th>
            <th>Prix d'une place</th>
        </tr>
        <?php
            $locale = new Zend_Locale('fr_FR');
            foreach ($this->lesVols as $unVol)
            {
                $unVol['dateHeureDepartPrevueVol'] = new Zend_Date($unVol['dateHeureDepartPrevueVol'], false, $locale);          
                $unVol['dateHeureArriveePrevueVol'] = new Zend_Date($unVol['dateHeureArriveePrevueVol'],false, $locale);          
                echo "<tr>";
                echo "<td>".$unVol['dateHeureDepartPrevueVol']->toString('EEEE dd MMMM yyyy à HH:mm')."</td>";
                echo "<td>".$unVol['dateHeureArriveePrevueVol']->toString(' EEEE dd MMMM yyyy à HH:mm')."</td>";
                if ($unVol['nbEscales'] == 0)
                {
                    echo "<td>Ligne directe (sans escale)</td>";
                }
                else
                {
                    echo "<td>".$unVol['nbEscales']." : <br /><ul>";
                    foreach ($this->lesEscales[$unVol['idVol']] as $lesEscalesduVol)
                    {
                        echo "<li>".$lesEscalesduVol['nomAeroport']."";
                        echo " (".$lesEscalesduVol['nomPays'].")<br /></li>";
                    }
                    echo "</ul></td>";
                }
                echo "<td>";
                foreach ($this->lesTarifs[$unVol['idVol']] as $lesTarifsDuVol)
                {
                     //Si ce n'est pas en promo
                    if ($lesTarifsDuVol['pourcentagePromo'] == 0)
                    {
                         echo $lesTarifsDuVol['nomClasse'].' : '.$lesTarifsDuVol['prixUnitaire'].' euros<br />';                
                    }
                    else 
                    {
                         //calcul du prix remisé
                         $nouveauPrix = (($lesTarifsDuVol['prixUnitaire'])*(1-($lesTarifsDuVol['pourcentagePromo'])/100));
                          echo $lesTarifsDuVol['nomClasse'].' : <b>'.$nouveauPrix; 
                          echo ' euros </b>(soit '.$lesTarifsDuVol['pourcentagePromo'].'% de réduction !)<br />';
                    }
                       
                }
                echo"</td>";
                echo "</tr>";
            }
        ?>
    </table> <br />
    <h2>Information</h2>
    <p>Pour réserver un vol, veuillez passer par l'administration en cliquant sur le bouton Connexion !</p>
</div>
