<h1>Consulter les vols disponibles</h1><br />

<p>Pour consulter les vols disponibles, choisissez tout d'abord une ligne :</p><br />


<div id="tableau">
    <table>
        <caption>Les lignes disponibles</caption>
        <tr>
            <th>Aéroport de départ</th>
            <th>Aéroport d'arrivée</th>
            <th>Périodicité du vol</th>
            <th>Nombre de vols disponibles</th>
            <th>Choisir</th>
        </tr>
        <?php
        foreach ($this->lignes as $ligne) {
            echo "<tr>";
            echo "<td>" . $ligne["aeroportDepart"] . "<br> " . $ligne["trigrammeAeroportDepart"] . "</td>";
            echo "<td>" . $ligne["aeroportArrivee"] . "<br> " . $ligne["trigrammeAeroportArrivee"] . "</td>";
            echo "<td>" . $ligne["nomPeriode"] . "</td>";
            echo "<td></td>";
            echo "<td><a href='#'>Choisir un vol de cette ligne</a></td>";
            echo "</tr>";
        }
        ?>   
        </table>
</div>
