<h1>Gestion des promotions</h1><br /><br />
<h2>Fonctionnement</h2>
<p>Retrouvez ci-dessous la liste des vols dont <b>le taux de remplissage est inférieur à 50%</b> et dont <b>le départ a lieu dans moins d'un mois</b>.</p><br/>

<h2>Liste des vols susceptibles d'être promotionnés</h2>
<div id="tableau">    
    <table>
        <caption>Liste des vols</caption>
        <tr>
            <th>Id</th>
            <th>Date de départ prévue</th>
            <th>Taux de remplissage</th>
            <th>Action</th>
        </tr>
    </table>
</div>
