				<footer>
					<p>Insset-Airline &copy; <?php echo date('Y'); ?></p><br/>
					<p><a href="">Mentions l&eacute;gales</a> - <a href="">Nous contacter</a> - <a href="">Plan du site</a></p>
				</footer>
			</div>
		</div>
	</div>
</div>


<?php /*		*/
	// creer un objet formulaire
	$monform = new Zend_Form;
	
	// parametrer le formulaire
	$monform->setMethod('post');
	$monform->setAction($this->baseUrl().'/index/connexion');
        $monform->setAttrib('id','form_login');
        
        $monform->addErrorMessage('test');
        
	//creer des elements de formulaires
	$eNom = new Zend_Form_Element_Text('input_user');
	$eNom->setLabel('Nom d\'utilisateur : ');
	
	$ePsw = new Zend_Form_Element_Password('input_psw');
	$ePsw->setLabel('Mot de passe : ');

        $eHidden = new Zend_Form_Element_Hidden('hid');
        $eHidden->setAttrib('id', 'err');
        
	$eBouton = new Zend_Form_Element_Button('bt_co');
	$eBouton->setLabel('Connexion');
        $eBouton->setAttrib('onclick','verifConnexion();');
	
        
        
	// ajout des elements au formulaire
	$monform->addElement($eNom);
	$monform->addElement($ePsw);
	$monform->addElement($eHidden);
        $monform->addElement($eBouton);
	
	
	echo '<div id=overlay>
		<div id=bt_fermer></div>';
	echo $monform;
	echo '</div>
            <div id=bglayer></div>';
?>

	


















