                            </section>				
                                <footer>
					<p>Insset-Airline &copy; <?php echo date('Y'); ?></p><br/>
					<p><a href="<?php echo $this->baseUrl(); ?>/index/mention">Mentions légales</a> - <a href="<?php echo $this->baseUrl(); ?>/index/contact">Nous contacter</a></p>
				</footer>
			</div>
		</div>
	</div>
</div>


<?php /*		*/
	// creer un objet formulaire
	$monform = new Zend_Form;
	
	// parametrer le formulaire
	$monform->setMethod('post');
	$monform->setAction($this->baseUrl().'/index/connexion');
        $monform->setAttrib('id','form_login');
        
	//creer des elements de formulaires
        $eRadio = new Zend_Form_Element_Radio('radio_form_co');
        $eRadio->setLabel(('Vous travaillez pour : '));
        $eRadio->addMultiOptions(array('Insset Airlines','Agence de voyage'));
        $eRadio->setSeparator('');
        $eRadio->setValue(0);
        $eRadio->setAttrib('id','bt_rad');
        
	$eNom = new Zend_Form_Element_Text('input_user');
	$eNom->setLabel('Nom d\'utilisateur : ');
        $eNom->setValue('admin');   // <- virer ca a la fin
	
	$ePsw = new Zend_Form_Element_Password('input_psw');
	$ePsw->setLabel('Mot de passe : ');

        $eHidden = new Zend_Form_Element_Hidden('hid');
        $eHidden->setAttrib('id', 'err');
        
	$eBouton = new Zend_Form_Element_Button('bt_co');
	$eBouton->setLabel('Connexion');
        $eBouton->setAttrib('onclick','verifConnexion();');       
        
	// ajout des elements au formulaire
	$monform->addElement($eNom);
	$monform->addElement($ePsw);
        $monform->addElement($eRadio);
	$monform->addElement($eHidden);
        $monform->addElement($eBouton);
	
	
	echo '<div id=overlay>
		<div id=bt_fermer></div>';
	echo $monform;
	echo '</div>
            <div class=bglayer></div>';
?>
