
<!-- /header	-->
<section class="section_contenu">
	<article>
		<!--  
		<fieldset class="article">
			<legend>Lorem ipsum</legend>
			<div class="article_cont">
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec orci auctor quam suscipit congue. Quisque ante turpis, imperdiet ut vulputate gravida, tempus ut nibh. Cras est leo, vulputate a feugiat auctor, mollis eu dui. Aenean vitae felis et erat volutpat tempus. In hac habitasse platea dictumst. Mauris justo nulla, convallis sed ullamcorper vel, viverra vitae augue. Suspendisse id tempor urna. Pellentesque malesuada ultricies orci, quis aliquam enim facilisis vitae. Proin blandit vehicula leo, ut volutpat odio egestas sit amet. Suspendisse suscipit enim condimentum ipsum accumsan scelerisque. Quisque porttitor tempus elit, id mollis tellus cursus vel. Curabitur feugiat lacus quis magna eleifend ut commodo neque pulvinar. Ut varius sem vitae leo tempor tristique in tincidunt urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
				<br/><br/>
				Nunc enim sem, egestas at rutrum eget, congue blandit neque. Maecenas tortor erat, congue quis dapibus id, volutpat et enim. Nulla porta, nunc id consequat consequat, ligula sem porta velit, in semper arcu ipsum at metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi porta auctor odio in laoreet. Quisque commodo velit urna, eget pretium justo. Quisque odio massa, interdum sed volutpat sed, mollis non nisi. Maecenas semper porta erat vel tempor.
				<br/><br/>
				Ut nibh magna, aliquam in lobortis ut, vestibulum ac augue. Suspendisse congue nisi vel mi sodales blandit. Nullam tempus augue ac odio aliquam aliquam. Proin molestie sodales nibh ut convallis. Proin lorem eros, rhoncus et laoreet et, scelerisque in tortor. Suspendisse rutrum pulvinar urna, quis pharetra velit pretium eu. Duis ullamcorper accumsan nisi, id vehicula metus vestibulum eget. Nulla tortor mi, porttitor quis tempus a, mollis non justo. Mauris fermentum dapibus leo, in pharetra libero dapibus vitae. Nullam ut nibh et orci vulputate tempus. Sed ac bibendum orci. Mauris eleifend mattis aliquet. Quisque non sapien urna. Morbi id imperdiet dui. Proin accumsan commodo odio ut tempus. Donec ac nunc in nunc luctus euismod.
				<br/><br/>
				Nulla in lectus non dui luctus porttitor. Nunc pharetra lacus lacinia mauris facilisis eget ultrices est rhoncus. Vivamus ultrices, felis vel sagittis porta, massa purus hendrerit urna, et luctus lacus ipsum ac libero. Phasellus eu enim urna, in tristique arcu. Nam interdum sodales lectus, sit amet hendrerit sapien fermentum quis. Pellentesque vel ipsum nec magna ullamcorper consectetur. Suspendisse tincidunt eleifend orci id gravida. Donec placerat arcu eget tortor malesuada convallis placerat arcu sollicitudin. Praesent rutrum urna eget lectus lobortis venenatis. Curabitur lacus urna, placerat at convallis non, rutrum pellentesque tortor. Duis eu massa felis. Etiam enim tellus, mattis eget accumsan eget, bibendum pulvinar libero. Mauris semper imperdiet ligula, vel placerat quam dignissim ac.
				<br/><br/>
				Praesent molestie feugiat tortor, sed dignissim diam aliquet eu. Mauris quis justo justo, nec volutpat lectus. Aliquam quis tellus lacus. Quisque non felis nec arcu dapibus sollicitudin tempus non diam. Ut fringilla sollicitudin fermentum. Etiam a ipsum mi, non imperdiet purus. Etiam turpis lorem, laoreet ut interdum quis, tristique in erat. In rutrum arcu nec justo varius egestas.
			</div>
		</fieldset>
		-->
		<script type="text/javascript">
		$(document).ready(function() {$('#slider').nivoSlider({effect:'fade', pauseTime: 5000});});
		</script>
		
		<div class="article_cont">
			<div class="slider-wrapper">
				<div id="slider" class="nivoSlider">
					<img src="<?php echo $this->baseUrl(); ?>/img/slides/slide_paris-marseille.jpg" />
					<img src="<?php echo $this->baseUrl(); ?>/img/slides/slide_iles_canaries.jpg" />
					<img src="<?php echo $this->baseUrl(); ?>/img/slides/slide_norvege.jpg" />
				</div>
			</div>
		</div>
	</article>
</section>
				


