<div id="tableau">    
    <table>
        <h2 id="centrer">Informations sur les vols</h2>
        <tr>
            <th>Ligne</th>
            <th>Vol</th>
            <th>Depart prévue</th>
            <th>Arrivée prévue</th>
            <th>Informations</th>
        </tr>
        <?php
            $lesRetards = $this->retards;
            foreach ($lesRetards as $unRetard) 
            {
                echo '<tr>';
                echo '<td>'.$unRetard["idLigne"].'</td>';
                echo '<td>'.$unRetard["idVol"].'</td>';
                echo '<td>'.$unRetard["dateHeureDepartPrevueVol"].'</td>';
                echo '<td>'.$unRetard["dateHeureArriveePrevueVol"].'</td>';
                echo '<td>'.$unRetard["remarqueVol"].'</td>';
                echo '</tr>';
            }
        ?>   
    </table>
</div>