<div id="appli">
    <h1 id="h1_dl_appli">Téléchargez notre application pour votre smartphone 
        <span id="andro">
             <img id="imgqrcode" src="<?php echo $this->baseUrl();?>/img/logoandroid.png" alt="Android"/>
        </span> !</h1>
    <div id="div_qrcode">
        <p id="p_android">
        Cliquez <a href="<?php echo $this->baseUrl();?>/android/insset_airlines.apk" id="lien_appli">ici</a>
        ou scannez ce QR code :
        </p>
        <div id="bg_qrcode">
           <img id="imgqrcode" src="<?php echo $this->baseUrl();?>/img/android.png" alt="application android"/>
        </div>
    </div>
</div>