<div id="appli">
    <h1 id="h1_dl_appli">Téléchargez notre application pour votre smartphone Android !</h1>
    <div id="div_qrcode">
        <a href="<?php echo $this->baseUrl();?>/android/insset_airlines.apk" id="lien_appli">Cliquez ici</a>
        ou scannez ce QR code :
        <div>
            <img id="imgqrcode" src="<?php echo $this->baseUrl();?>/img/qrcode_inssetairlines.png" alt="application android" width="200" height="200"/>
        </div>
    </div>
</div>