<?php echo $this->doctype('HTML5'); ?>
<html>
<head>
	<title>INSSET AirLines</title>
        <link rel="icon" type="images/png" href="<?php echo $this->baseUrl();?>/img/template/favicon.png" />
        
	<!-- 		CSS		-->
	<link type="text/css" href="<?php echo $this->baseUrl();?>/css/template/reset.css" rel="stylesheet" />
	<link type="text/css" href="<?php echo $this->baseUrl();?>/css/template/header_footer.css" rel="stylesheet" />
	<link type="text/css" href="<?php echo $this->baseUrl();?>/css/overlay.css"rel="stylesheet" />
	<link type="text/css" href="<?php echo $this->baseUrl();?>/css/template/base.css" rel="stylesheet" />
	<link type="text/css" href="<?php echo $this->baseUrl();?>/css/nivo-slider.css"rel="stylesheet" />
	<link type="text/css" href="<?php echo $this->baseUrl();?>/css/android.css"rel="stylesheet" />
	<link type="text/css" href="<?php echo $this->baseUrl();?>/css/planning.css"rel="stylesheet" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/template/jquery-ui-1.9.0.custom.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/planif.css" />
        
	<!--		JAVASCRIPT		
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.min.js"></script>-->
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/overlay.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/menu.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.nivo.slider.pack.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-ui-1.9.0.custom.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/planning.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/base.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/planification.js"></script>
        
</head>
<body>
<?php
	echo $this->layout()->header;

	echo $this->layout()->content; 

	echo $this->layout()->footer;
?>

</body>
</html>
