<?php
    // affiche le message s'il y en a un
    if (!empty($this->message))
    {
        echo $this->message[0]; 
    }
    // si on a trouvé une ligne
    if($this->laLigne)
    {
        echo '<br><h3>Vous modifiez la ligne : <br></h3><h1>'.$this->laLigne['depart'].' -> '.$this->laLigne['arrivee'].'</h1><br>'; 
      
        // on affiche le formulaire de modification de ligne
        echo $this->formModif;
    }
    else
    {
        // message d'erreur, ligne non trouvée
        echo '<p>Cette ligne n\'existe pas. Veuillez vérifier les entrées</p>';
    }
?>
    <a href="/directionstrategique" class="retour" id="ret">Retour</a>